<?php

/**
 * @file
 * Contains ridelog.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ridelog_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ridelog module.
    case 'help.page.ridelog':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Paul&#039;&#039;s Ride Log') . '</p>';
      return $output;

    default:
  }
}

