<?php

/**
 * @file
 * Contains ridelog.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ridelog_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ridelog module.
    case 'help.page.ridelog':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Paul&#039;&#039;s Ride Log') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ridelog_theme() {
	$templates['ridelog'] = [
		'render element' => 'children',
		'variables' => [
			'rides' => [
				'ride1' => [
				'title' => 'Ride1',
				'bike'  => 'Grando',
				'miles' => '99',
				'date'  => '2023-12-25',
				],
			],
		],	
	];
    $templates['yeartotals'] = [
		'render element' => 'children',
		'variables' => [
			'bikes'	=> ['year'],
		    'rides' => ['year' => ['month' => ['bike' => 'miles',],],],    			
    		'year_total'  => ['year' => 'miles'],
    		'month_total' => ['year' => ['month' => 'miles']],
    		'bike_total' => ['year' => ['bike' => 'miles']],	
    		'stats'      => ['year' => [
				'total' => 100,
				'long'  => 50,
				'avg'   => 20,
				'count' => 10,
			  ],
            ],	
            'grand'   => [
                'miles' => 100000,
                'rides' => 1000,
                'avg'   => 5000,
            ],
    	],
    ];
    $templates['yearlysummary'] = [
		'render element' => 'children',
		'variables' => [
			'yearly'  => ['year' => [
				'total' => 100,
				'long'  => 50,
				'avg'   => 20,
				'count' => 10,
			  ],
			],
		],
	];
	$templates['monthsummary'] = [
		'render element' => 'children',
		'variables' => [
			'monthly' => ['month' => [
				'total' => 100,
				'long'  => 50,
				'avg'   => 20,
				'count' => 10,
				],
			],
		],
	];
     $templates['years'] = [
		'render element' => 'children',
		'variables' => [
			'years'  => ['year' => [
				'miles' => 100,
			  ],
			],
		],
	];
	   
    return $templates;	
    
}


    		
